version: "3.8"

services:
  # Todo Frontend
  

  # Todo Backend API
  api:
    build:
      dockerfile: Dockerfile
      context: ./todo-backend
      # Only builds development stage from the dockerfile
      target: development
    volumes:
      - ./todo-backend:/deepak/src/app
      - /deepak/src/app/node_modules
    # In dev mode: npm run start:dev / In debug mode: npm run start:debug
    command: npm run start:dev
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      JWT_SECRET: hlaskdhaio1237891aa
    ports:
      - "3000:3000"

  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 35000:5432

  postgres_admin:
    image: dpage/pgadmin4:6.12
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80